//Prompt para corrigir, complementar e reorganizar texto para melhorar a boa compreensão
const varTextoCorrigir = "Sou Escrivão da Polícia Civil de Minas Gerais e estou trabalhando em um Auto de Prisão em Flagrante Delito. Baseado no seguinte texto, por favor:\n\n- Analise e, se necessário, corrija, complemente e reestruture para facilitar a compreensão. Como é um texto no contexto policial, palavras ofensivas não devem ser suprimidas;\n- Remova frases irrelevantes, que não forneçam informações factuais;\n- Elimine segmentos excessivamente prolixos e desnecessários;\n- Como se trata de um Auto de Prisão em Flagrante Delito, substitua os pontos finais por pontos-e-vírgulas, e comece cada frase com Que…\n\nO texto é esse:";

//Otimizar a linguagem do texto (mantendo o QUE e ponto-e-vírgula)
const varTextoOtimizar = "Sou Escrivão da Polícia Civil de Minas Gerais e estou trabalhando em um Auto de Prisão em Flagrante Delito. Baseado no seguinte texto, por favor:\n\n- Analise e, se necessário, corrija e reestruture levemente a língua portuguesa utilizada para melhorar a compreensão, sem inventar informações ou nomes, e sem suprimir informações;\n- Como é um texto no contexto policial, palavras ofensivas não devem ser suprimidas;\n- Como se trata de um Auto de Prisão em Flagrante Delito, a formatação de dividir as frases por pontos-e-vírgulas, e começar cada frase com o termo Que… deve ser mantida;\n\nO texto é esse:";

//Reorganizar texto
const varTextoReorganizar = "Analise e otimize o texto a seguir, corrigindo qualquer confusão, complementando onde necessário e reorganizando para melhorar a compreensão. O texto é:";

//Formatar com Que e com ponto-e-vírgula
const varTextoQUEPontoeVirgula = "Sou Escrivão da Polícia Civil de Minas Gerais e estou trabalhando em um Auto de Prisão em Flagrante Delito. Tenho um texto para você editar seguindo estes critérios:\n\n- Substitua cada ponto final por um ponto-e-vírgula.\n- Inicie cada frase com a palavra Que, e ajuste a gramática e ortografia conforme necessário para manter a coerência e o sentido das frases.\n- Como é um texto no contexto policial, palavras ofensivas não devem ser suprimidas.\n\nPor favor, processe essa solicitação no texto que fornecerei a seguir:";

//Prompt do condutor do flagrante
const varTextoCondutor = "Sou Escrivão da Polícia Civil de Minas Gerais e estou trabalhando em um Auto de Prisão em Flagrante Delito. Baseado no seguinte texto, elabore o depoimento do Condutor do Flagrante para um Auto de Prisão em Flagrante Delito. Seguem diretrizes:\n\n- Separe frases com ponto-e-vírgula, sem exceções;\n- Inicie cada frase com o termo Que… \n- Use principalmente a terceira pessoa do singular;\n- Inicie o texto assim: Que neste ato é ouvido na condição de Condutor e Primeira Testemunha; Que é Policial Militar e que nesta data […];\n- Mencione o nome completo do envolvido, e em caixa alta, apenas na sua primeira ocorrência no texto, e use somente o primeiro nome nas menções seguintes, sem necessidade de caixa alta. Se não tiver a informação do nome completo do envolvido, não invente nomes;\n- Evite pronomes de tratamento;\n- Conclua o texto com o seguinte desfecho: Que [nome do autor] recebeu voz de prisão em flagrante delito e foi conduzido para a Delegacia de Polícia Civil de Pouso Alegre para procedimentos;\n- Não mencione os artigos da lei pela qual a prisão foi efetuada;\n- Refira-se aos envolvidos pelos seus nomes próprios, mesmo que isso seja gramaticalmente repetitivo;\n- Se necessário, corrija e reestruture levemente a língua portuguesa utilizada para melhorar a compreensão, sem inventar informações ou nomes, e sem suprimir informações;\n- Use vocabulário adequado para textos jurídicos;\n- Como é um texto no contexto policial, palavras ofensivas não devem ser suprimidas;\n- Exclua referências a garantias de direitos constitucionais.\n\nO texto é esse:";

//Prompt do condutor do flagrante, para formatar o texto
const varTextoCondutorFormatar = "Sou Escrivão da Polícia Civil de Minas Gerais e estou trabalhando em um Auto de Prisão em Flagrante Delito. Dada a seguinte situação, formate o texto abaixo de acordo com as seguintes regras para ser a oitiva de um condutor do flagrante em um Auto de Prisão em Flagrante Delito:\n\n- Frases devem ser separadas por ponto-e-vírgula ao invés de ponto final.\n- Iniciar cada frase com o termo: Que..., ajustando a gramática e a ortografia, conforme necessário.\n- Comece o texto com a frase: Que neste ato é ouvido na condição de Condutor e Primeira Testemunha; Que é Policial Militar e que nesta data...\n- Conclua o texto com uma das seguintes opções, dependendo se algum material foi apreendido ou não: a) Que [nome do autor] recebeu voz de prisão em flagrante delito e foi conduzido para a Delegacia de Polícia Civil de Pouso Alegre para procedimentos. b) Que [nome do autor] recebeu voz de prisão em flagrante delito e foi conduzido juntamente com os materiais arrecadados para a Delegacia de Polícia Civil de Pouso Alegre para procedimentos.\n- O texto deve ser escrito na terceira pessoa do singular.\n- Como é um texto no contexto policial, palavras ofensivas não devem ser suprimidas.\n\nO texto é esse:";

//Prompt da testemunha policial do flagrante
const varTextoTestemunha = "Sou Escrivão da Polícia Civil de Minas Gerais e estou trabalhando em um Auto de Prisão em Flagrante Delito. Por favor, reescreva o texto a seguir de acordo com as diretrizes listadas abaixo:\n\n- Substitua o cabeçalho: Que neste ato é ouvido na condição de Condutor e Primeira Testemunha, por: Que neste ato é ouvido na condição de Segunda Testemunha; Que é Policial Militar e que nesta data acompanhou as diligências que culminaram na voz de prisão ao conduzido.\n- Realize uma leve reorganização do texto, sem alterar o conteúdo original, para garantir que esta versão seja distinta da anterior.\n- Mantenha os verbos arrecadado e arrecadada, caso ocorram, pois eles não devem ser substituídos.\n- Mude o desfecho do texto, onde se lê: Que o autor recebeu voz de prisão..., para: Que o condutor do flagrante deu voz de prisão ao conduzido e o encaminhou para a Delegacia de Polícia Civil de Pouso Alegre para procedimentos.\n- Siga o formato de que cada frase começa com o termo: Que... e que as frases são divididas por ponto-e-vírgula.\n- Mantenha a redação geral do texto na terceira pessoa do singular.\n- Como é um texto no contexto policial, palavras ofensivas não devem ser suprimidas.\n\nO texto é esse:";

//Prompt de outras testemunhas
const varTextoTestemunhaOutras = "Sou Escrivão da Polícia Civil de Minas Gerais e estou trabalhando em um Auto de Prisão em Flagrante Delito. Transforme o depoimento do condutor do flagrante, apresentado abaixo, no depoimento da testemunha ___, respeitando as seguintes regras:\n\n- Cada frase inicia com o termo Que...\n- As frases são separadas entre si por ponto-e-vírgula, sem exceções;\n- A testemunha deve se referir a si mesma como: depoente;\n- Esclareça no início se a testemunha tem algum vínculo com o autor ou se não há nenhum;\n- Escreva na terceira pessoa do singular;\n- Adapte o relato para parecer que a testemunha está descrevendo o que aconteceu hoje, onde, quando, e como, usando verbos no passado;\n- Escreva como se a testemunha estivesse narrando os fatos nesse momento, na delegacia;\n- Não mencione a condução do autor à delegacia;\n- Use letras minúsculas, exceto ao citar os nomes dos envolvidos pela primeira vez;\n- Inclua apenas o depoimento da testemunha, sem citar as declarações de outros envolvidos;\n- Refira-se aos envolvidos pelos seus nomes, sem usar termos como vítima ou autor;\n- Como é um texto no contexto policial, palavras ofensivas não devem ser suprimidas.\n\nA oitiva do condutor do flagrante é:";

//Prompt da vítima, a partir de tópicos resumidos (BETA)
const varTextoVitimaA = "A partir dos tópicos resumidos abaixo, escrever a oitiva da vítima do flagrante, em que as regras são:\n- O texto, no geral, deve ser escrito sem caixa alta, em que as letras maiúsculas devem ser usadas somente nos nomes próprios, e o nome dos envolvidos deve ser escrito em caixa alta;\n- Cada frase começa sempre com o termo em maiúsculo QUE. E as frases são divididas por ponto-e-vírgula, e jamais por ponto final (o ponto final vai somente no final do texto);\n- O texto deve ser escrito, no geral, na terceira pessoa do singular;\n- Quando a vítima se referir a ela mesmo, deve ser utilizado a expressão: declarante. Por exemplo: QUE a declarante disse que o conduzido a agrediu com um soco na região da face;\n- Complementar os tópicos resumidos, de modo a conter uma boa semântica e um raciocínio completo.\n\nOs tópicos resumidos são esses:";

//Promt da vítima, a partir da oitiva do condutor do flagrante
const varTextoVitimaB = "Sou Escrivão da Polícia Civil de Minas Gerais e estou trabalhando em um Auto de Prisão em Flagrante Delito. Reescreva a declaração do condutor no Auto de Prisão em Flagrante Delito, assumindo a perspectiva da vítima ___. Utilize as seguintes diretrizes:\n\n- Comece todas as frases com o termo Que...\n- Separe as frases por ponto-e-vírgula, sem exceções;\n- Referir-se à vítima como: declarante;\n- No início do texto, informe o vínculo da vítima com o autor, se houver essa informação;\n- Escreva na terceira pessoa do singular;\n- Baseando-se na declaração do condutor do flagrante, reescreva como se fosse a vítima narrando o que ocorreu, indicando onde, quando e como os eventos se desenrolaram. Os verbos geralmente estão no passado, pois os eventos já ocorreram.\n- Apresente a narração como se estivesse acontecendo agora, durante o depoimento na delegacia;\n- Não inclua a informação de que o autor foi levado à delegacia;\n- Utilize letras minúsculas, exceto na primeira vez em que os nomes dos envolvidos são mencionados;\n- Inclua apenas a perspectiva da vítima, sem declarações de outros envolvidos;\n- Evite se referir aos envolvidos como vítima ou autor. Use seus nomes próprios, mesmo que cause repetição;\n- Como é um texto no contexto policial, palavras ofensivas não devem ser suprimidas.\n\nA oitiva do condutor do flagrante é:";

//Prompt da vítima de crime de Maria da Penha
const varTextoVitimaMariadaPenha = "Sou Escrivão da Polícia Civil de Minas Gerais e estou trabalhando em um Auto de Prisão em Flagrante Delito. Reescreva a declaração do condutor no Auto de Prisão em Flagrante Delito, assumindo a perspectiva da vítima ___, a qual foi vítima de crime previsto na Lei Maria da Penha. Utilize as seguintes diretrizes:\n\n- Comece todas as frases com o termo Que...;\n- Separe as frases por ponto-e-vírgula, sem exceção;\n- Referir-se à vítima como: declarante;\n- No início, informe o vínculo da vítima com o autor, caso tiver essa informação;\n- Escreva na terceira pessoa do singular;\n- Baseando-se na declaração do condutor do flagrante, reescreva como se fosse a vítima narrando o que ocorreu, indicando onde, quando e como os eventos se desenrolaram. Os verbos geralmente estão no passado, pois os eventos já ocorreram;\n- Apresente a narração como se estivesse acontecendo agora, durante o depoimento na delegacia;\n- Não inclua a informação de que o autor foi levado à delegacia;\n- Utilize letras minúsculas, exceto na primeira vez em que os nomes dos envolvidos são mencionados;\n- Inclua apenas a perspectiva da vítima, sem declarações de outros envolvidos.\n- Evite se referir aos envolvidos como vítima ou autor. Use seus nomes próprios, mesmo que cause repetição;\n- Ao final, insira que a vítima tem interesse em representar criminalmente contra o agressor, e que tem interesse que lhe sejam deferidas medidas protetivas de urgência para o agressor não se aproxime de si e não mantenha contato;\n- Como é um texto no contexto policial, palavras ofensivas não devem ser suprimidas.\n\nA oitiva do condutor do flagrante é:";

//Prompt do autor, a partir da oitiva do condutor do flagrante
const varTextoAutorA = "Sou Escrivão da Polícia Civil de Minas Gerais e estou trabalhando em um Auto de Prisão em Flagrante Delito. Escreva o depoimento do autor ___, com base na oitiva abaixo do condutor do flagrante. Mantenha as seguintes diretrizes:\n\n- Comece todas as frases com o termo: Que...\n- Separe as frases com ponto-e-vírgula, sem exceções;\n- Substitua referências ao autor por: declarante;\n- Mantenha a narração na terceira pessoa do singular;\n- Reescreva o depoimento do condutor do flagrante como se fosse o autor relatando os eventos. Os eventos devem ser descritos como ocorridos no passado, como se o autor estivesse relatando em tempo real na delegacia;\n- Evite mencionar a condução do autor para a delegacia;\n- Utilize letras minúsculas, exceto para os nomes dos envolvidos quando mencionados pela primeira vez;\n- Inclua apenas as declarações do autor, a partir da perspectiva dele, sem menção às declarações de outros envolvidos;\n- Evite referir-se aos envolvidos como vítima ou autor, e utilize os nomes próprios, mesmo que cause repetição;\n- Como é um texto no contexto policial, palavras ofensivas não devem ser suprimidas.\n\nA oitiva do condutor do flagrante é:";

//Prompt para perguntas ao conduzido
const varPerguntasConduzido = "Sou Escrivão da Polícia Civil em Minas Gerais e estou trabalhando em um Auto de Prisão em Flagrante Delito. Em breve, irei ouvir o conduzido/autor relacionado ao caso. A partir da oitiva do condutor do flagrante, abaixo, quais perguntas você recomendaria que eu fizesse ao acusado para esclarecer os detalhes deste crime?\n";

//Prompt para perguntas à vítima
const varPerguntasVitima = "Sou Escrivão da Polícia Civil em Minas Gerais e estou trabalhando em um Auto de Prisão em Flagrante Delito. Eu ouvi a vítima relacionada ao caso. A partir da oitiva da vítima do flagrante, abaixo, quais perguntas você recomendaria que eu fizesse à vítima para esclarecer e complementar os detalhes deste crime?\n";

//Prompt para perguntas ao condutor do flagrante
const varPerguntasCondutor = "Sou Escrivão da Polícia Civil em Minas Gerais e estou trabalhando em um Auto de Prisão em Flagrante Delito. Já ouvi o policial militar responsável pela condução do flagrante. Com base na oitiva (depoimento) do condutor, gostaria de saber quais perguntas você recomendaria que eu fizesse ao policial militar. O objetivo é esclarecer e complementar os detalhes deste crime e avaliar se realmente ocorreu uma infração criminal. Além disso, quero assegurar que não houve nenhum abuso de autoridade por parte do policial militar durante a prisão em flagrante:\n";

//Prompt para perguntas à testemunha
const varPerguntasTestemunha = "Sou Escrivão da Polícia Civil em Minas Gerais e estou trabalhando em um Auto de Prisão em Flagrante Delito. Realizei a oitiva do condutor do flagrante, que é o policial militar responsável pelo caso. Quais perguntas você recomendaria que eu fizesse à testemunha para esclarecer e complementar os detalhes deste crime?\n";

//Modelo de texto do Auto de Apreensão
const varTextoApreensao = "Os materiais arrecadados no REDS ___ foram recebidos, conferidos e lacrados pela equipe de investigadores plantonistas.";

//Ofício do presídio
const varTextoPresidio = "Seguem anexos cópias do Despacho Ratificador, da Nota de Culpa e de Ciências das Garantias Fundamentais, da Ficha de Antecedentes Criminais, do Fato Policial e do Auto de Prisão em Flagrante Delito.";

//Ofício da justiça, quando se libera mediante fiança
const varTextoJusticaFianca = "O conduzido teve sua liberdade restituída mediante o pagamento da fiança estipulada.";

//Ofício da justiça, quando se libera devido a despacho não ratificado
const varTextoJusticaNRat = "O conduzido foi restituído à sua liberdade haja vista que, após análise dos elementos probatórios e fundamentos apresentados, a Autoridade Policial competente, nos termos do Código de Processo Penal, optou por não ratificar a prisão em flagrante delito, não subsistindo os motivos ensejadores da medida, sendo assim, o indivíduo foi posto em liberdade sem prejuízo das investigações em curso.";

//Despacho de transferência, em razão do local
const varTextoLocal = "força da competência em razão do local da consumação do ilícito, estabelecendo a unidade policial responsável por dar seguimento às averiguações e apurações pertinentes ao caso.";

//Despacho de transferência, em razão da matéria
const varTextoMateria = "força da competência em razão da matéria, para a unidade policial especializada que detém a atribuição de conduzir as investigações do fato criminoso e adotar as medidas cabíveis.";

//Textos das Utilidades
//Conduzido que se nega a assinar
const varTextoNaoAssinou = "O conduzido, após ser devidamente interrogado perante a Autoridade Policial competente, optou por não apor sua assinatura no respectivo Auto de Prisão em Flagrante Delito e na Nota de Culpa e de Ciências das Garantias Fundamentais. Cumpre ressaltar que o conduzido foi devidamente cientificado acerca dos seus direitos constitucionais e garantias processuais, conforme preceitua a legislação vigente. Neste ato, registra-se a recusa do referido indivíduo em formalizar sua aquiescência aos mencionados documentos, os quais, não obstante, foram devidamente lavrados em conformidade com os ditames legais e normativos aplicáveis.\n\n\nO conduzido ___ optou por não apor sua assinatura no respectivo ciente do Mandado de Prisão, com a justificativa que ele já cumpriu a pena relacionada ao processo ___, e expressou preocupação de que, se fosse encaminhado ao presídio, não seria liberado novamente. Cumpre ressaltar que o conduzido foi devidamente cientificado acerca dos seus direitos constitucionais e garantias processuais, conforme preceitua a legislação vigente. Neste ato, registra-se a recusa do referido indivíduo em formalizar sua aquiescência aos mencionados documentos, os quais, não obstante, foram devidamente lavrados em conformidade com os ditames legais e normativos aplicáveis.";

//Militar que não participou da ocorrência
const varTextoPMNao = "Que é Policial Militar, e que não estava presente nas diligências que culminaram na voz de prisão ao conduzido, mas que, por imperativo do comando hierárquico, coube ao depoente a incumbência de encaminhar o conduzido a esta Delegacia de Polícia Civil, haja vista a rotatividade de plantões laborais da Polícia Militar;"

//Mandado de prisão
const varTextoMandado = "Comunicação de Cumprimento de Mandado de Prisão [nome do preso] [número do processo]\n\nMM. Juiz(a) de Direito e Ilustres Servidores(as) do Poder Judiciário,\n\nVenho por meio desta, em cumprimento às determinações do Excelentíssimo Delegado de Polícia, Dr. [nome do Delegado], transmitir a Vossa Excelência e aos digníssimos(as) servidores(as) da justiça a devida ciência acerca do cumprimento do mandado de prisão em desfavor de [nome do preso], conforme preceitua o Mandado de Prisão oriundo dos autos processuais de nº [número do processo].\n\nEncontrará anexado a este e-mail o ofício elaborado em atenção ao cumprimento da medida restritiva de liberdade supracitada, ratificando a materialização do ato emanado por este douto juízo.\n\nRespeitosamente,\nMarcus Mota Crabbi\nEscrivão de Polícia";

//Conduzido embriagado
const varConduzidoEmbriagado = "PARA OITIVA: no momento da apresentação do conduzido nesta unidade policial, ele se encontrava em estado de embriaguez acentuada e apresentava comportamento extremamente agressivo, tornando inviável a realização de seu interrogatório pela Autoridade Policial. ___ proferia palavras desconexas e incoerentes, demonstrando não possuir condições de compreender o teor das perguntas que lhe seriam formuladas, bem como de prestar declarações com discernimento. Diante das circunstâncias, não foi possível ouvir o conduzido nesta data.\nPARA CERTIDÃO: nesta data, de 6 de maio de 2023, foi conduzido a esta Delegacia de Polícia Civil, o indivíduo de nome ___, de RG ___, e que, no momento da apresentação do conduzido nesta unidade policial, ele se encontrava em estado de embriaguez acentuada e apresentava comportamento extremamente agressivo, tornando inviável a realização de seu interrogatório pela Autoridade Policial. ___ proferia palavras desconexas e incoerentes, demonstrando não possuir condições de compreender o teor das perguntas que lhe seriam formuladas, bem como de prestar declarações com discernimento. Diante das circunstâncias, não foi possível ouvir o conduzido nesta data.";

//PJe Indisponível
const varPjeIndisponivel = "EMAIL DE APFD\nComunicação de Auto de Prisão em Flagrante Delito - [Nome do autor] - Sistema PJe indisponível\nMM. Juiz(a) de Direito e Ilustres Servidores(as) do Poder Judiciário,\nVenho por meio desta, em cumprimento às determinações do Excelentíssimo Delegado de Polícia, Dr. [nome delegado], comunicar e encaminhar a Vossa Excelência e aos digníssimos(as) servidores(as) da justiça o Auto de Prisão em Flagrante Delito de [nome do autor], ocorrido na data de [data do fato], no município de [município];.\nRessalto que a comunicação está sendo realizada por email, tendo em vista que o sistema PJe (Processo Judicial Eletrônico) encontra-se indisponível no momento.\nEm anexo a este email, segue o arquivo .pdf que contém o Auto de Prisão em Flagrante Delito digitalizado, para conhecimento e providências cabíveis por parte deste respeitável órgão do Poder Judiciário.\nCertos de sua compreensão quanto à indisponibilidade do sistema PJe, e cientes da importância do devido processo legal, nos colocamos à disposição para eventuais esclarecimentos que se façam necessários.\nRespeitosamente,\nMarcus Mota Crabbi\nEscrivão de Polícia\nMODELO DE EAMP\nComunicação de Expediente Apartado de Medidas Protetivas - [nome da vítima] - Sistema PJe indisponível\nMM. Juiz(a) de Direito e Ilustres Servidores(as) do Poder Judiciário,\nVenho por meio desta, em cumprimento às determinações do Excelentíssimo Delegado de Polícia, Dr. [nome delegado], comunicar e encaminhar a Vossa Excelência e aos digníssimos(as) servidores(as) da justiça Expediente Apartado de Medidas Protetivas de [nome da vítima] em face de [nome do conduzido].\nRessalto que a comunicação está sendo realizada por email, tendo em vista que o sistema PJe (Processo Judicial Eletrônico) encontra-se indisponível no momento.\nEm anexo a este email, segue o arquivo .pdf que contém o Expediente Apartado de Medidas Protetivas digitalizado, para conhecimento e providências cabíveis por parte deste respeitável órgão do Poder Judiciário.\nCertos de sua compreensão quanto à indisponibilidade do sistema PJe, e cientes da importância do devido processo legal, nos colocamos à disposição para eventuais esclarecimentos que se façam necessários.\nRespeitosamente,\nMarcus Mota Crabbi\nEscrivão de Polícia";

//Hospital que não forneceu documentação médica para o plantão
const varHospitalDocMedica = "no presente plantão, lavrado nesta unidade policial, a unidade hospitalar não forneceu a documentação médica da vítima para ser apresentada no plantão policial. Informo ainda que a documentação médica em questão será requisitada pela equipe policial do expediente, visando a devida instrução do procedimento e a garantia dos direitos da vítima. Por ser verdade, dou fé e lavro a presente certidão, que segue assinada por mim.";

//Encaminhamento de AAFAI e de adolescente infrator ao Promotor de Justiça
const varAAFAI = "Assunto: Encaminhamento de Auto de Apreensão em Flagrante de Ato Infracional e adolescente infrator\nExcelentíssimo(a) Senhor(a) Promotor(a) de Justiça,\n\nPor meio do presente ofício, vimos respeitosamente encaminhar a Vossa Excelência o Auto de Apreensão em Flagrante de Ato Infracional, lavrado nesta Delegacia de Polícia Civil, referente ao adolescente infrator KAIQUE JUNIOR ADAO DE SOUZA, e encaminhar KAIQUE para apreciação do presente caso por Vossa Excelência, de acordo com as disposições normativas aplicáveis.\n\nO mencionado ato infracional ocorreu no dia 7 de maio de 2023, no bairro São Geraldo, no município de Pouso Alegre, consistindo na prática de tentativa de homicídio. O adolescente KAIQUE JUNIOR ADAO DE SOUZA foi apreendido em flagrante pela equipe policial e foi conduzido à Delegacia de Pouso Alegre para lavratura do Auto de Apreensão em Flagrante de Ato Infracional, onde ele ficou acautelado em seção isolada dos adultos e com instalações apropriadas.\n\nReiteramos nossos votos de estima e consideração, colocando-nos à disposição para quaisquer esclarecimentos adicionais que se fizerem necessários.\nRespeitosamente,";

//Comunicar cartório central que mandado não pôde ser comunicado devido a falta de internet
const varMandadoSemInternet = "Ao Cartório Central,\n\nO mandado de prisão não pôde ser comunicado à justiça durante meu plantão devido à interrupção da internet externa aos sistemas da polícia. Fiquei sem acesso ao email, impossibilitando a comunicação do procedimento. Os demais computadores disponíveis durante o plantão também estavam sem internet, funcionando somente o PCNET, REDS e SIP.\nConcedi acesso a todos do Cartório Central e fiz a juntada do mandado assinado pelo preso.\n\nAtenciosamente,\nMarcus Mota Crabbi";

//Falta de material de escritório
const varMaterialEscritorio = "Ao Cartório Central,\n\nVenho por meio desta comunicar que durante o meu plantão noturno do dia 1 de outubro de 2023 constatei a falta de colchetes disponíveis em nossos suprimentos de escritório, impedindo a adequada montagem dos APFD e demais procedimentos.\nEsta falta inesperada e involuntária de material indispensável afetou, portanto, a adequada conclusão das tarefas a mim atribuídas durante o plantão, impossibilitando a entrega dos documentos de forma devidamente montada e pronta para o devido trâmite legal subsequente.\n\nAgradeço pela compreensão.\n\n\nAtenciosamente,\nMarcus Mota Crabbi\nEscrivão de Polícia";